// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/storage/metricDbStorage.go
//
// Generated by this command:
//
//	mockgen -source=./internal/storage/metricDbStorage.go -destination ./internal/service/server/mock_db_storage_test.go -package server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDbStorage is a mock of DbStorage interface.
type MockDbStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDbStorageMockRecorder
}

// MockDbStorageMockRecorder is the mock recorder for MockDbStorage.
type MockDbStorageMockRecorder struct {
	mock *MockDbStorage
}

// NewMockDbStorage creates a new mock instance.
func NewMockDbStorage(ctrl *gomock.Controller) *MockDbStorage {
	mock := &MockDbStorage{ctrl: ctrl}
	mock.recorder = &MockDbStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDbStorage) EXPECT() *MockDbStorageMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockDbStorage) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDbStorageMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDbStorage)(nil).Ping), ctx)
}
